import Image from "next/image";
import Link from "next/link";

/** Local AVIF — generated by `npm run optimize-images` (<200KB). */
export const HERO_LCP_SRC = "/images/hero/hero.avif";

const HEADLINE_LINES = [
  "Crafting Extraordinary",
  "Experiences",
  "For Extraordinary People",
] as const;

/**
 * Server-rendered homepage hero — static markup for fast LCP, no client JS.
 */
export function HeroStatic() {
  return (
    <section
      id="welcome"
      aria-label="Hero"
      className="relative flex min-h-[100svh] items-center overflow-hidden border-b border-[var(--glitz-border)] bg-black"
    >
      <div className="absolute inset-0">
        <Image
          src={HERO_LCP_SRC}
          alt=""
          fill
          priority
          fetchPriority="high"
          sizes="100vw"
          className="object-cover"
          aria-hidden
        />
        <div className="absolute inset-0 bg-black/55" aria-hidden />
      </div>

      <div className="brand-container relative z-10 w-full py-24 pb-28 text-center sm:py-28">
        <p className="hero-brand-tagline mb-4 text-[10px] font-semibold uppercase tracking-[0.28em] text-white/80 sm:text-[11px]">
          The Next Era of Celebrations
        </p>

        <h1 className="nex-hero-text mx-auto font-[family-name:var(--font-playfair)] font-bold text-white">
          {HEADLINE_LINES.map((line, i) => (
            <span
              key={line}
              className={
                i === HEADLINE_LINES.length - 1
                  ? "mt-0.5 block text-[var(--glitz-gold,#d4af37)]"
                  : "block"
              }
            >
              {line}
            </span>
          ))}
        </h1>

        <p className="mx-auto mt-5 max-w-[36rem] text-[clamp(0.9375rem,0.9rem+0.25vw,1.0625rem)] leading-relaxed text-white/85">
          Nexyyra Events designs luxury weddings, destination celebrations, corporate
          experiences, celebrity events and unforgettable moments across India.
        </p>

        <div className="mt-8 flex w-full flex-col items-center justify-center gap-3 sm:flex-row sm:flex-wrap">
          <Link
            href="/book-event"
            className="btn-gold-metallic tap-target inline-flex min-h-[48px] w-full min-w-0 items-center justify-center rounded-lg px-8 py-3 text-sm font-semibold tracking-wide sm:min-w-[12.5rem] sm:w-auto"
          >
            Book Consultation
          </Link>
          <Link
            href="/portfolio"
            className="tap-target inline-flex min-h-[48px] w-full min-w-0 items-center justify-center rounded-lg border border-[var(--glitz-gold,#d4af37)]/45 bg-black/30 px-8 py-3 text-sm font-semibold tracking-wide text-white hover:border-[var(--glitz-gold,#d4af37)]/70 sm:min-w-[12.5rem] sm:w-auto"
          >
            View Portfolio
          </Link>
        </div>
      </div>
    </section>
  );
}
