/* eslint-disable */
/** Auto-generated by npm run media:sync — do not edit manually */
export const GENERATED_BRAND_IMAGES = {
  "hero": {
    "video": "",
    "poster": "/images/venues/SMB_6785.JPG",
    "wedding": "/images/venues/4F1A7866.JPG",
    "corporate": "/images/venues/0T5A9825.JPG",
    "palace": "/images/venues/0T5A8668.JPG"
  },
  "weddings": [
    "/images/weddings/0T5A9528.JPG",
    "/images/weddings/0T5A9523.JPG",
    "/images/weddings/0T5A9454.JPG",
    "/images/weddings/0T5A9297.JPG",
    "/images/weddings/0T5A9268.JPG",
    "/images/weddings/0T5A9248.JPG"
  ],
  "corporate": [
    "/images/placeholders/corporate-coming-soon.png",
    "/images/placeholders/corporate-coming-soon.png",
    "/images/placeholders/corporate-coming-soon.png",
    "/images/placeholders/corporate-coming-soon.png"
  ],
  "destinations": [
    "/images/placeholders/destination-coming-soon.png",
    "/images/placeholders/destination-coming-soon.png",
    "/images/placeholders/destination-coming-soon.png",
    "/images/placeholders/destination-coming-soon.png"
  ],
  "venues": [
    "/images/venues/SMB_6785.JPG",
    "/images/venues/4F1A7866.JPG",
    "/images/venues/0T5A9825.JPG",
    "/images/venues/0T5A8668.JPG",
    "/images/venues/0T5A8667.JPG",
    "/images/venues/0T5A8660.JPG",
    "/images/venues/0T5A8658.JPG",
    "/images/venues/0T5A8656.JPG"
  ],
  "vendors": [
    "/images/gallery/0T5A9804.JPG",
    "/images/gallery/0T5A9799.JPG",
    "/images/gallery/0T5A9792.JPG",
    "/images/gallery/0T5A9775.JPG"
  ],
  "gallery": [
    "/images/gallery/0T5A9804.JPG",
    "/images/gallery/0T5A9799.JPG",
    "/images/gallery/0T5A9792.JPG",
    "/images/gallery/0T5A9775.JPG",
    "/images/gallery/0T5A9765.JPG",
    "/images/gallery/0T5A9762.JPG",
    "/images/gallery/0T5A8892.JPG",
    "/images/gallery/0T5A8811.JPG",
    "/images/gallery/0T5A8805.JPG",
    "/images/gallery/0T5A8798.JPG",
    "/images/gallery/SMB_6916.JPG",
    "/images/gallery/SMB_6908.JPG"
  ],
  "blog": [
    "/images/gallery/0T5A9804.JPG",
    "/images/gallery/0T5A9799.JPG",
    "/images/gallery/0T5A9792.JPG"
  ],
  "contact": "/images/venues/4F1A7866.JPG",
  "about": "/images/weddings/0T5A9523.JPG",
  "catering": "/images/gallery/0T5A9792.JPG",
  "decor": "/images/weddings/0T5A9454.JPG",
  "awards": "/images/gallery/0T5A9775.JPG",
  "testimonials": [
    "/images/weddings/0T5A9528.JPG",
    "/images/weddings/0T5A9523.JPG",
    "/images/weddings/0T5A9454.JPG"
  ]
} as const;

export const GENERATED_HERO_SLIDES = [
  {
    "category": "Grand Ballroom",
    "video": "",
    "poster": "/images/venues/SMB_6785.JPG",
    "alt": "SMB 6785 — Nexyyra Events"
  },
  {
    "category": "Palace Estate",
    "video": "",
    "poster": "/images/venues/4F1A7866.JPG",
    "alt": "4F1A7866 — Nexyyra Events"
  },
  {
    "category": "Luxury Venue",
    "video": "",
    "poster": "/images/venues/0T5A9825.JPG",
    "alt": "0T5A9825 — Nexyyra Events"
  },
  {
    "category": "Heritage Hall",
    "video": "",
    "poster": "/images/venues/0T5A8668.JPG",
    "alt": "0T5A8668 — Nexyyra Events"
  },
  {
    "category": "Garden Pavilion",
    "video": "",
    "poster": "/images/venues/0T5A8667.JPG",
    "alt": "0T5A8667 — Nexyyra Events"
  },
  {
    "category": "Convention Suite",
    "video": "",
    "poster": "/images/venues/0T5A8660.JPG",
    "alt": "0T5A8660 — Nexyyra Events"
  }
] as const;
