/** Auto-generated by npm run media:sync / media:regen — do not edit manually (curate in image-curation.ts) */
export const GENERATED_BRAND_IMAGES = {
  "hero": {
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1FMEA0jCZXKEfSl7QRzbslrjYDW50Kn3i=w1920",
    "wedding": "https://lh3.googleusercontent.com/d/1lJbfeSwmJtcckYFyav_XCLban-GILGHX=w1920",
    "corporate": "https://lh3.googleusercontent.com/d/1XTyhxvPesVuTo6p5iWr3BFX9LrBC5C9W=w1920",
    "palace": "https://lh3.googleusercontent.com/d/1SqaF7yzJN702yZJIeGWSIDcSj7wTvclY=w1920"
  },
  "weddings": [
    "https://lh3.googleusercontent.com/d/1GtY7ck6bcQEMTJsCR5C7xAWS7jSPomr9=w1920",
    "https://lh3.googleusercontent.com/d/1BdaCjf0Xk-Vvh43QOi-YhKe8ioHZy0Ai=w1920",
    "https://lh3.googleusercontent.com/d/1D8_JM11YOZhdtQ_iyLylF0rW3zfIBNg5=w1920",
    "https://lh3.googleusercontent.com/d/1zZDjOmcrunL0OabHO-dPYLCH3xPZlLEy=w1920",
    "https://lh3.googleusercontent.com/d/1I0TH9jcxQFoXm0YzG4f4rFWaiTzlixW0=w1920",
    "https://lh3.googleusercontent.com/d/1SGW0HH_6JgU_xpOMsyt3SL0R6MkB0URk=w1920"
  ],
  "corporate": [
    "https://lh3.googleusercontent.com/d/1kDdjV4TpcglIMteJOjBrAB2JOsALq3Mq=w1920",
    "https://lh3.googleusercontent.com/d/1kfdbQXzMTtx5l4Cbd0NMcnHsSrNjb3-I=w1920",
    "https://lh3.googleusercontent.com/d/1n3lfTSgS-952kOnOZVv8tTz0PPrTfRC2=w1920",
    "https://lh3.googleusercontent.com/d/1lT00v7aMGMqSg8_rr1ooLteStd366itK=w1920"
  ],
  "destinations": [
    "https://lh3.googleusercontent.com/d/1zeuLostJ9lEvQXgaYzTPOeuPsbbN3CSd=w1920",
    "https://lh3.googleusercontent.com/d/14Q8S6tU76seiJLeD1SU2RkiiNUYT4SP7=w1920",
    "https://lh3.googleusercontent.com/d/1EEZdabeWrt_sl3wuhZn-VvdSMIx6VA8B=w1920",
    "https://lh3.googleusercontent.com/d/12O55-1UOeO22Iav2uwv6f9sOVbTFAl0l=w1920"
  ],
  "venues": [
    "https://lh3.googleusercontent.com/d/10yDcl4wHuk6mMImwCaB6WPwMWmAoRfW5=w1920",
    "https://lh3.googleusercontent.com/d/131RPh47oY4c9iflke0JALMHs_znZzrb1=w1920",
    "https://lh3.googleusercontent.com/d/1VpfNcwb3XG1-UMc4CkwV4gdlSZrTJpfe=w1920",
    "https://lh3.googleusercontent.com/d/1KEqaLeJksvJosN1aOKzcS3PUPPwAP9n2=w1920",
    "https://lh3.googleusercontent.com/d/1pBkjJhGY7jIYlRJSM9LbPtOZbCHf4yx1=w1920",
    "https://lh3.googleusercontent.com/d/1lJbfeSwmJtcckYFyav_XCLban-GILGHX=w1920",
    "https://lh3.googleusercontent.com/d/1SqaF7yzJN702yZJIeGWSIDcSj7wTvclY=w1920",
    "https://lh3.googleusercontent.com/d/1kI5dyUe3ISc7EUbxSRTSiHE9vtpxUO4S=w1920"
  ],
  "vendors": [
    "https://lh3.googleusercontent.com/d/1c5nKDx-AEuP223fKQFSOe0j_-bzLUn1D=w1920",
    "https://lh3.googleusercontent.com/d/1akR7zJ8Lg01GWB8WtvWwO1Z9krIVXDxM=w1920",
    "https://lh3.googleusercontent.com/d/1nVjxfKzy1gAWPaviMZRfg9cAwEvv8fN1=w1920",
    "https://lh3.googleusercontent.com/d/17DxJ-fiRjOAPYvrFS7fihCNj0MlCrnk2=w1920"
  ],
  "gallery": [
    "https://lh3.googleusercontent.com/d/1FMEA0jCZXKEfSl7QRzbslrjYDW50Kn3i=w1920",
    "https://lh3.googleusercontent.com/d/1lJbfeSwmJtcckYFyav_XCLban-GILGHX=w1920",
    "https://lh3.googleusercontent.com/d/1GtY7ck6bcQEMTJsCR5C7xAWS7jSPomr9=w1920",
    "https://lh3.googleusercontent.com/d/1BdaCjf0Xk-Vvh43QOi-YhKe8ioHZy0Ai=w1920",
    "https://lh3.googleusercontent.com/d/1D8_JM11YOZhdtQ_iyLylF0rW3zfIBNg5=w1920",
    "https://lh3.googleusercontent.com/d/1c5nKDx-AEuP223fKQFSOe0j_-bzLUn1D=w1920",
    "https://lh3.googleusercontent.com/d/1SqaF7yzJN702yZJIeGWSIDcSj7wTvclY=w1920",
    "https://lh3.googleusercontent.com/d/1kI5dyUe3ISc7EUbxSRTSiHE9vtpxUO4S=w1920",
    "https://lh3.googleusercontent.com/d/1zZDjOmcrunL0OabHO-dPYLCH3xPZlLEy=w1920",
    "https://lh3.googleusercontent.com/d/1I0TH9jcxQFoXm0YzG4f4rFWaiTzlixW0=w1920",
    "https://lh3.googleusercontent.com/d/1SGW0HH_6JgU_xpOMsyt3SL0R6MkB0URk=w1920",
    "https://lh3.googleusercontent.com/d/1akR7zJ8Lg01GWB8WtvWwO1Z9krIVXDxM=w1920"
  ],
  "blog": [
    "https://lh3.googleusercontent.com/d/1jnDexINl4RAHm5reI6PmJic9mEs-GBbi=w1920",
    "https://lh3.googleusercontent.com/d/147PGDAUEppxiw0JurWGNJvQnG12ru2Ax=w1920",
    "https://lh3.googleusercontent.com/d/1gPjYLh5nG39vdxbIp8g6ippQwAOsFiEP=w1920"
  ],
  "contact": "https://lh3.googleusercontent.com/d/1ULB06kE7vj6_riTJFUTT63dJhgg5jerY=w1920",
  "about": "https://lh3.googleusercontent.com/d/1kI5dyUe3ISc7EUbxSRTSiHE9vtpxUO4S=w1920",
  "catering": "https://lh3.googleusercontent.com/d/1LVol5mo2COi0uTusmsMN8heF6G3y6sRE=w1920",
  "decor": "https://lh3.googleusercontent.com/d/1aOjM7cEE5U8ZbLOntuAmRP99tqvL2X7v=w1920",
  "awards": "https://lh3.googleusercontent.com/d/1VIAcBZrkLhzQwQoO1VDxYEv8MLOTrxsV=w1920",
  "testimonials": [
    "https://lh3.googleusercontent.com/d/1wHacY8pfh5VniudcsZnXbsq4QwOy_1Mg=w1920",
    "https://lh3.googleusercontent.com/d/1gwXQ4oHSU0CRUbhtY4n-EM1GFrhb1OQ5=w1920",
    "https://lh3.googleusercontent.com/d/1cV9LAUnE0wYIoXUiI9LzePnu9-aq-el5=w1920"
  ]
};

export const GENERATED_HERO_SLIDES = [
  {
    "category": "Grand Entrance",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1FMEA0jCZXKEfSl7QRzbslrjYDW50Kn3i=w1920",
    "alt": "Sky-blue entrance gate with a coral layered arch and tall floral pillars opening onto a pastel geometric pathway",
    "focal": "50% 55%"
  },
  {
    "category": "Reception Stage",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1lJbfeSwmJtcckYFyav_XCLban-GILGHX=w1920",
    "alt": "Ivory ballroom stage with white floral arches, chandeliers and a pink loveseat",
    "focal": "50% 55%"
  },
  {
    "category": "Poolside Celebration",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1kI5dyUe3ISc7EUbxSRTSiHE9vtpxUO4S=w1920",
    "alt": "Resort pool beneath a rainbow lantern canopy with a pastel floral backdrop and a flower-filled boat",
    "focal": "50% 40%"
  },
  {
    "category": "Reception Stage",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1zZDjOmcrunL0OabHO-dPYLCH3xPZlLEy=w1920",
    "alt": "Pastel pink stage with floral-crowned window cut-outs, a red loveseat and banks of yellow and pink flowers",
    "focal": "50% 60%"
  },
  {
    "category": "Stage Production",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1XTyhxvPesVuTo6p5iWr3BFX9LrBC5C9W=w1920",
    "alt": "Performers on a stage between cold-spark fountains with a blue galaxy LED backdrop",
    "focal": "50% 50%"
  },
  {
    "category": "Grand Entrance",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1EEZdabeWrt_sl3wuhZn-VvdSMIx6VA8B=w1920",
    "alt": "Colourful entrance walkway with pink wavy arches, hanging tassels and floral urns",
    "focal": "50% 60%"
  },
  {
    "category": "Couple Moment",
    "video": "",
    "poster": "https://lh3.googleusercontent.com/d/1GtY7ck6bcQEMTJsCR5C7xAWS7jSPomr9=w1920",
    "alt": "Couple in mint-green outfits seated in a flower-lined navy boat on a foam-covered pool in warm haze",
    "focal": "60% 55%"
  }
] as const;
